name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set Image Tag
        run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/dominate2/horizonzerodawnmachinescrud:$IMAGE_TAG --tag ghcr.io/dominate2/horizonzerodawnmachinescrud:latest
          docker login ghcr.io -u dominate2 -p ${{secrets.TOKENSANG}}
          docker push ghcr.io/dominate2/horizonzerodawnmachinescrud:$IMAGE_TAG
          docker push ghcr.io/dominate2/horizonzerodawnmachinescrud:latest
